Repository AthennaIO/Database, pull requests merged in 2022-09, with the labels that each got.

#2 Feat/vic create new commands
  package-lock.json
  package.json
  src/Commands/Db/Seed.js
  src/Commands/Db/Wipe.js
  src/Commands/Make/Resource.js
  src/Commands/Migration/Revert.js
  src/Commands/Migration/Run.js
  src/Helpers/DatabaseCommandsLoader.js
  src/Helpers/Resource.js
  src/Models/Model.js
  src/Models/ModelQueryBuilder.js
  src/index.d.ts
  src/index.js
  templates/__name__Resource.js.ejs
  tests/Stubs/app/Resources/UserResource.js
  tests/Stubs/configs/app.js
  tests/Stubs/configs/database.js
  tests/Stubs/database/migrations/ProductMigration1661308536493.js
  tests/Stubs/database/migrations/UserMigration1661308536492.js
  tests/Stubs/database/seeders/UserSeeder.js
  tests/Stubs/models/User.js
  tests/Unit/Commands/Db/SeedTest.js
  tests/Unit/Commands/Db/WipeTest.js
  tests/Unit/Commands/Make/ResourceTest.js
  tests/Unit/Commands/Migration/RevertTest.js
  tests/Unit/Commands/Migration/RunTest.js
  tests/Unit/Models/UserModelTest.js
Labels: feature

#4 Fix/vic find or fail exception code
  package.json
  src/Exceptions/NotFoundDataException.js
Labels: bug

#18 feat(columns): improve columns to be more simple to write the model schema
  package.json
  src/Drivers/MySqlDriver.js
  src/Drivers/PostgresDriver.js
  src/Exceptions/ConnectionFailedException.js
  src/Factories/DriverFactory.js
  src/Models/Column.js
  src/index.d.ts
  tests/Stubs/configs/logging.js
  tests/Stubs/models/Product.js
  tests/Stubs/models/ProductMySql.js
  tests/Stubs/models/User.js
  tests/Stubs/models/UserMySql.js
Labels: chore, feature, fix, refactor, test
